// GENERATED by BN-Builder · screen "Dashboard"
// Structure is owned by the builder. Logic edits: BN:LOGIC block only. Do not remove data-bn-id.

import { AppSidebar } from '@/components/app-sidebar';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';

// ── BN:LOGIC:BEGIN ── do not move, do not reformat ──
// ── BN:LOGIC:END ──

export default function Dashboard() {
  return (
    <div data-bn-id="n1" className="flex">
      <SidebarProvider data-bn-id="n2" defaultOpen="true">
        <AppSidebar data-bn-id="n3" />
        <SidebarInset data-bn-id="n4">
          <div data-bn-id="n5" className="flex flex-col">
            <div data-bn-id="n6" className="flex flex-row gap-2 items-center border-b px-4 h-12">
              <SidebarTrigger data-bn-id="n7" className="-ml-1" />
              <Separator data-bn-id="n8" orientation="vertical" className="h-4 mr-2" />
              <h1 data-bn-id="n9" className="text-lg font-semibold">Dashboard</h1>
            </div>
            <div data-bn-id="n10" className="grid gap-4 p-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
              <Card data-bn-id="n11" className="w-full">
                <CardHeader data-bn-id="n12">
                  <CardTitle data-bn-id="n13" text="Revenue" />
                  <CardDescription data-bn-id="n14" text="Last 30 days" />
                </CardHeader>
                <CardContent data-bn-id="n15">$45,231</CardContent>
              </Card>
              <Card data-bn-id="n17" className="w-full">
                <CardHeader data-bn-id="n18">
                  <CardTitle data-bn-id="n19" text="Users" />
                  <CardDescription data-bn-id="n20" text="Active users" />
                </CardHeader>
                <CardContent data-bn-id="n21">+2,350</CardContent>
              </Card>
              <Card data-bn-id="n23" className="w-full">
                <CardHeader data-bn-id="n24">
                  <CardTitle data-bn-id="n25" text="Sales" />
                  <CardDescription data-bn-id="n26" text="Today" />
                </CardHeader>
                <CardContent data-bn-id="n27">+12,234</CardContent>
              </Card>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
