import { describe, it, expect } from 'vitest';
import { generateScreen } from './generate';
import type { ScreenSpec } from '../core/ir';

// Login screen from Appendix A of AGENTS.md
const LOGIN_SPEC: ScreenSpec = {
  version: 1,
  id: 's1',
  name: 'Login',
  route: '/login',
  tokens: {
    colors: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      primary: '#171717',
      primaryForeground: '#fafafa',
      secondary: '#f5f5f5',
      secondaryForeground: '#737373',
      muted: '#f5f5f5',
      mutedForeground: '#737373',
      accent: '#f5f5f5',
      accentForeground: '#171717',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      destructive: '#dc2626',
      destructiveForeground: '#fafafa',
      border: '#e5e5e5',
      input: '#e5e5e5',
    },
    radius: 10,
    fonts: { sans: 'Inter', display: 'Unbounded' },
  },
  root: {
    kind: 'layout',
    id: 'n1' as never,
    display: 'flex',
    direction: 'column',
    gap: 4,
    align: 'center',
    justify: 'center',
    className: 'min-h-screen',
    children: [
      {
        kind: 'component',
        id: 'n2' as never,
        component: 'Card',
        className: 'w-80',
        children: [
          {
            kind: 'component',
            id: 'n3' as never,
            component: 'CardHeader',
            children: [
              {
                kind: 'component',
                id: 'n4' as never,
                component: 'CardTitle',
                children: [{ kind: 'text', id: 'n5' as never, text: 'Вход в аккаунт' }],
              },
            ],
          },
          {
            kind: 'component',
            id: 'n6' as never,
            component: 'CardContent',
            children: [
              {
                kind: 'component',
                id: 'n7' as never,
                component: 'Input',
                props: { placeholder: 'Email' },
                events: { onChange: 'onEmail' },
              },
              {
                kind: 'component',
                id: 'n8' as never,
                component: 'Button',
                className: 'w-full',
                events: { onClick: 'submit' },
                children: [{ kind: 'text', id: 'n9' as never, text: 'Войти' }],
              },
            ],
          },
        ],
      },
    ],
  },
};

describe('generateScreen', () => {
  it('generates TSX matching Appendix B structure', () => {
    const { tsx } = generateScreen(LOGIN_SPEC);

    // Header
    expect(tsx).toContain('// GENERATED by BN-Builder · screen "Login"');
    expect(tsx).toContain(
      '// Structure is owned by the builder. Logic edits: BN:LOGIC block only. Do not remove data-bn-id.',
    );

    // Imports in alphabetical order
    const importSection = tsx.substring(0, tsx.indexOf('// ──'));
    expect(importSection).toContain("import { Button } from '@/components/ui/button'");
    expect(importSection).toContain(
      "import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'",
    );
    expect(importSection).toContain("import { Input } from '@/components/ui/input'");

    // button before card before input (alphabetical)
    const buttonIdx = importSection.indexOf('button');
    const cardIdx = importSection.indexOf('card');
    const inputIdx = importSection.indexOf('input');
    expect(buttonIdx).toBeLessThan(cardIdx);
    expect(cardIdx).toBeLessThan(inputIdx);

    // Export style
    expect(tsx).toContain('export default function Login() {');

    // data-bn-id on nodes
    expect(tsx).toContain('data-bn-id="n1"');
    expect(tsx).toContain('data-bn-id="n2"');
    expect(tsx).toContain('data-bn-id="n4"');

    // className order: data-bn-id first, then className
    const n1Line = tsx.split('\n').find((l) => l.includes('data-bn-id="n1"'));
    expect(n1Line).toMatch(/data-bn-id="n1".*className=/);

    // Single text child => inline
    expect(tsx).toContain('<CardTitle data-bn-id="n4">Вход в аккаунт</CardTitle>');
    expect(tsx).toContain(
      '<Button data-bn-id="n8" className="w-full" onClick={submit}>Войти</Button>',
    );

    // Self-closing for no children
    expect(tsx).toContain('<Input data-bn-id="n7" placeholder="Email" onChange={onEmail} />');
    expect(tsx).toContain('<CardHeader data-bn-id="n3">');
    expect(tsx).toContain('<CardContent data-bn-id="n6">');

    // LOGIC block
    expect(tsx).toContain('function onEmail(/* args */) { /* TODO */ }');
    expect(tsx).toContain('function submit(/* args */) { /* TODO */ }');
  });

  it('generates CSS in oklch format', () => {
    const { css } = generateScreen(LOGIN_SPEC);
    expect(css).toContain('@import "tailwindcss";');
    expect(css).toContain(':root {');
    expect(css).toContain('--background:');
    expect(css).toContain('oklch(');
    expect(css).toContain('@theme inline {');
    expect(css).toContain('--font-sans: "Inter"');
    expect(css).toContain('--font-display: "Unbounded"');
    expect(css).toContain('--radius: 0.625rem;');
    expect(css).toContain('--ring: var(--primary);');
    expect(css).toContain('@layer base {');
  });

  it('generates htmlHead with font links', () => {
    const { htmlHead } = generateScreen(LOGIN_SPEC);
    expect(htmlHead).toContain('fonts.googleapis.com');
    expect(htmlHead).toContain('Inter');
    expect(htmlHead).toContain('Unbounded');
  });

  it('re-generation preserves LOGIC block', () => {
    // First generation
    const first = generateScreen(LOGIN_SPEC);
    // Manually edit the LOGIC block (simulating external agent)
    const editedTsx = first.tsx.replace(
      'function onEmail(/* args */) { /* TODO */ }',
      'function onEmail(e: React.ChangeEvent<HTMLInputElement>) { /* validate email */ }',
    );

    // Re-generate with prevTsx
    const second = generateScreen(LOGIN_SPEC, { prevTsx: editedTsx });

    // Old handlers preserved
    expect(second.tsx).toContain(
      'function onEmail(e: React.ChangeEvent<HTMLInputElement>) { /* validate email */ }',
    );
    expect(second.tsx).toContain('function submit(/* args */) { /* TODO */ }');
  });

  it('adds stubs for new events on re-generation', () => {
    // First generation with no events on Card
    const spec1: ScreenSpec = {
      ...LOGIN_SPEC,
      root: {
        ...LOGIN_SPEC.root,
        children: [
          {
            kind: 'component',
            id: 'n2' as never,
            component: 'Card',
            className: 'w-80',
            children: [
              {
                kind: 'component',
                id: 'n10' as never,
                component: 'CardHeader',
                children: [],
              },
            ],
          },
        ],
      },
    };

    const first = generateScreen(spec1);
    const editedTsx = first.tsx.replace(
      '// ── BN:LOGIC:BEGIN ── do not move, do not reformat ──',
      '// ── BN:LOGIC:BEGIN ── do not move, do not reformat ──\nfunction existingFn() { /* implemented */ }',
    );

    // Add a new screen with an event
    const spec2: ScreenSpec = {
      ...spec1,
      root: {
        ...spec1.root,
        children: [
          {
            kind: 'component',
            id: 'n2' as never,
            component: 'Card',
            className: 'w-80',
            events: { onClick: 'handleCardClick' },
            children: [
              {
                kind: 'component',
                id: 'n10' as never,
                component: 'CardHeader',
                children: [],
              },
            ],
          },
        ],
      },
    };

    const second = generateScreen(spec2, { prevTsx: editedTsx });

    // Old function preserved
    expect(second.tsx).toContain('function existingFn() { /* implemented */ }');
    // New function got a stub
    expect(second.tsx).toContain('function handleCardClick(/* args */) { /* TODO */ }');
  });
});
