import { describe, it, expect } from 'vitest'
import { defaultStubs, preserveLogic, LOGIC_BEGIN, LOGIC_END } from './logic'
import type { ScreenSpec } from '../core/ir'

function makeSpec(events: Record<string, Record<string, string>>): ScreenSpec {
  return {
    version: 1,
    id: 'test',
    name: 'Test',
    route: '/test',
    tokens: {
      colors: {
        background: '#ffffff', foreground: '#0a0a0a', card: '#ffffff',
        primary: '#171717', primaryForeground: '#fafafa',
        muted: '#f5f5f5', mutedForeground: '#737373',
        accent: '#f5f5f5', accentForeground: '#171717',
        destructive: '#dc2626', destructiveForeground: '#fafafa',
        border: '#e5e5e5', input: '#e5e5e5',
      },
      radius: 10,
      fonts: { sans: 'Inter' },
    },
    root: {
      kind: 'layout', id: 'n1' as never,
      display: 'flex', direction: 'column',
      children: Object.entries(events).map(([component, evts]) => ({
        kind: 'component' as const,
        id: `n${component}` as never,
        component,
        events: evts,
        children: [],
      })),
    },
  }
}

describe('defaultStubs', () => {
  it('returns empty block when there are no events', () => {
    const spec = makeSpec({})
    expect(defaultStubs(spec)).toBe(LOGIC_BEGIN + '\n' + LOGIC_END + '\n')
  })

  it('generates stubs for all unique handlers', () => {
    const spec = makeSpec({
      Button: { onClick: 'handleClick' },
      Input: { onChange: 'handleChange' },
    })
    const result = defaultStubs(spec)
    expect(result).toContain(LOGIC_BEGIN)
    expect(result).toContain(LOGIC_END)
    expect(result).toContain('function handleClick(/* args */) { /* TODO */ }')
    expect(result).toContain('function handleChange(/* args */) { /* TODO */ }')
  })

  it('deduplicates handlers with the same name', () => {
    const spec = makeSpec({
      Button: { onClick: 'handleClick' },
      Card: { onClick: 'handleClick' },
    })
    const result = defaultStubs(spec)
    expect(result).toContain('function handleClick(/* args */) { /* TODO */ }')
    // Only one occurrence
    expect(result.match(/function handleClick/g)).toHaveLength(1)
  })
})

describe('preserveLogic', () => {
  it('returns nextTsx unchanged when prevTsx has no LOGIC block', () => {
    const prev = 'export default function Foo() { return <div /> }'
    const next = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction foo() { /* TODO */ }\n${LOGIC_END}\nexport default function Foo() { return <div /> }`
    expect(preserveLogic(prev, next)).toBe(next)
  })

  it('preserves old LOGIC block verbatim', () => {
    const prev = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction handleClick(e) { console.log(e) }\n${LOGIC_END}\nexport default function Foo() {}`
    const next = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction handleClick(/* args */) { /* TODO */ }\n${LOGIC_END}\nexport default function Foo() {}`
    const result = preserveLogic(prev, next)
    expect(result).toContain('function handleClick(e) { console.log(e) }')
    expect(result).not.toContain('/* TODO */')
  })

  it('adds stubs for new handlers not in old block', () => {
    const prev = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction oldHandler() { /* already implemented */ }\n${LOGIC_END}\nexport default function Foo() {}`
    const next = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction newHandler(/* args */) { /* TODO */ }\nfunction oldHandler(/* args */) { /* TODO */ }\n${LOGIC_END}\nexport default function Foo() {}`
    const result = preserveLogic(prev, next)
    // Old handler preserved
    expect(result).toContain('function oldHandler() { /* already implemented */ }')
    // New handler got default stub
    expect(result).toContain('function newHandler(/* args */) { /* TODO */ }')
  })

  it('does not duplicate handlers that exist in both', () => {
    const prev = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction foo() { return 42; }\n${LOGIC_END}\nexport default function Bar() {}`
    const next = `// GENERATED by BN-Builder\n${LOGIC_BEGIN}\nfunction foo(/* args */) { /* TODO */ }\n${LOGIC_END}\nexport default function Bar() {}`
    const result = preserveLogic(prev, next)
    // Old version preserved, no duplicate
    expect(result).toContain('function foo() { return 42; }')
    expect(result.match(/function foo/g)).toHaveLength(1)
  })
})
